{ "display_name":"Memcached collectd Plugin",
  "description": "Memcached collectd plugin",
  "code": "https://github.com/collectd/collectd/blob/master/src/memcached.c",
  "featured": true,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-memcached/img/integrations_memcached.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-memcached/img/integrations_memcached%402x.png"
}
