{ "display_name":"Memcached",
  "description": "Monitor Memcached using the SignalFx collectd agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-memcached",
  "code": "https://github.com/signalfx/collectd/blob/master/src/memcached.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-memcached/img/integrations_memcached.png",
  "logo_small": "/images/repos/collectd-memcached/img/integrations_memcached%402x.png",
  "in_app_categories": ["servicesMonitored"]
}
