{ "display_name":"MySQL collectd Plugin",
  "description": "MySQL collectd plugin",
  "code": "https://github.com/collectd/collectd/blob/master/src/mysql.c",
  "featured": true,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-mysql/img/integrations_mysql.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-mysql/img/integrations_mysql%402x.png"
}
