{ "display_name":"Couchbase collectd Plugin",
  "description": "Couchbase collectd plugin",
  "code": "https://github.com/signalfx/collectd-couchbase",
  "featured": false,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-couchbase/img/integrations_couchbase.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-couchbase/img/integrations_couchbase%402x.png"
}
