{ "display_name":"Varnish collectd Plugin",
  "description": "Varnish collectd plugin",
  "code": "https://github.com/collectd/collectd/blob/master/src/varnish.c",
  "featured": false,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-varnish/img/integrations_varnish.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-varnish/img/integrations_varnish%402x.png"
}
