{ "display_name":"ZooKeeper collectd Plugin",
  "description": "ZooKeeper collectd plugin",
  "code": "https://github.com/collectd/collectd/blob/master/src/zookeeper.c",
  "featured": false,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-zookeeper/img/integrations_zookeeper.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-zookeeper/img/integrations_zookeeper%402x.png"
}
