{ "display_name":"NGINX collectd Plugin",
  "description": "NGINX collectd plugin",
  "code": "https://github.com/collectd/collectd/blob/master/src/nginx.c",
  "featured": false,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-nginx/img/integrations_nginx.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-nginx/img/integrations_nginx%402x.png"
}
