{ "display_name":"ElasticSearch collectd Plugin",
  "description": "ElasticSearch collectd Plugin",
  "code": "https://github.com/signalfx/collectd-elasticsearch",
  "featured": true,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-elasticsearch/img/integrations_elasticsearch.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-elasticsearch/img/integrations_elasticsearch%402x.png"
}
