{ "display_name":"PostgreSQL collectd Plugin",
  "description": "PostgreSQL collectd plugin",
  "code": "https://github.com/collectd/collectd/blob/master/src/postgresql.c",
  "featured": false,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-postgresql/img/integrations_postgresql.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-postgresql/img/integrations_postgresql%402x.png"
}
