{ "display_name":"Kafka collectd Plugin",
  "description": "Kafka collectd plugin",
  "code": "https://github.com/collectd/collectd/blob/master/bindings/java/org/collectd/java/GenericJMX.java",
  "featured": true,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-kafka/img/integrations_kafka.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-kafka/img/integrations_kafka%402x.png"
}
