{ "display_name":"Docker collectd Plugin",
  "description": "Docker collectd Plugin",
  "code": "https://github.com/signalfx/docker-collectd-plugin",
  "featured": true,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-docker/img/integrations_docker.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-docker/img/integrations_docker%402x.png"
}
