{ "display_name":"Redis collectd Plugin",
  "description": "Redis collectd plugin",
  "code": "https://github.com/collectd/collectd/blob/master/src/redis.c",
  "featured": false,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-redis/img/integrations_redis.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-redis/img/integrations_redis%402x.png"
}
