{ "display_name":"RabbitMQ collectd Plugin",
  "description": "RabbitMQ collectd plugin",
  "code": "https://github.com/signalfx/collectd-rabbitmq",
  "featured": false,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-rabbitmq/img/integrations_rabbitmq.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-rabbitmq/img/integrations_rabbitmq%402x.png"
}
