{ "display_name":"cAdvisor Metrics Plugin",
  "description": "cAdvisor metrics plugin",
  "code": "https://github.com/signalfx/cadvisor-integration",
  "featured": false,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-cadvisor/img/integrations_cadvisor.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-cadvisor/img/integrations_cadvisor%402x.png"
}
