{ "display_name":"SignalFx collectd",
  "description": "SignalFx validated version of collectd",
  "code": "https://github.com/signalfx/collectd",
  "featured": true,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd/img/integrations_collectd%402x.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd/img/integrations_collectd.png"
}
