{ "display_name":"AppDynamics Metrics Plugin",
  "description": "AppDynamics metrics plugin",
  "code": "https://github.com/signalfx/appd-integration",
  "featured": false,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-appdynamics/img/integrations_appdynamics.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-appdynamics/img/integrations_appdynamics%402x.png"
}
