{ "display_name":"MongoDB collectd Plugin",
  "description": "MongoDB collectd plugin",
  "code": "https://github.com/signalfx/collectd-mongodb",
  "featured": true,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd-mongodb/img/integrations_mongodb.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd-mongodb/img/integrations_mongodb%402x.png"
}
