{ "display_name":"cURL-JSON collectd Plugin",
  "description": "collectd plugin to gather metrics through cURL in JSON format ",
  "code": "https://github.com/collectd/collectd/blob/master/src/curl_json.c",
  "featured": false,
  "logo_large": "https://github.com/signalfx/Integrations/blob/master/collectd/img/integrations_collectd%402x.png",
  "logo_small": "https://github.com/signalfx/Integrations/blob/master/collectd/img/integrations_collectd.png"
}
